### ISSUE TITLE
IllegalStateException: refreshAfterWrite requires a LoadingCache

### ISSUE THREAD

**Issue by Dogacel** [be-hase/caffeine-coroutines#14]
Seems like the coroutine loader is not extending `LoadingCache` thus causing issues with `refreshAfterWrite` operation.

Reprod:
```kotlin
private val headSchemaCache: CoroutineLoadingCache<Unit, String> =
    Caffeine.newBuilder()
        .maximumSize(10)
        .expireAfterWrite(60.seconds.toJavaDuration())
        .refreshAfterWrite(10.seconds.toJavaDuration())
        .buildCoroutine {
            delay(1000)
            "Foo"
        }
```

**Comment by be-hase** [comment]
@Dogacel 
Thank you for the report. Let me consider how to fix this. 🙏

**Comment by be-hase** [comment]
@Dogacel 
Fixed by https://github.com/be-hase/caffeine-coroutines/releases/tag/v1.2.0
Please check.
